// src/components/Card.jsx
// import React, { useState } from 'react';

export default function Card({
  // Props (settings)
  href,
  title,
  body,
  // Props (styles)
  elemBase = "card",
  elemHeading = "h2",
  restBase = "",
  restHeading = "",
  background = "bg-slate-800",
}) {
  return (
      <>
        <a href={href} className={[`${elemBase} ${background} ${restBase}`]}>
          <h2 className={[`${elemHeading} ${restHeading}`]}>{title}</h2>
          <p>{body}</p>
        </a>
      </>
  )
};

// src/components/Card/Card.svelte
<script lang="ts">
  // Props (settings)
  export let href: string;
  export let title: string;
  export let body: string;

  // Props (styles)
  export let elemBase = "card";
  export let elemHeading = "h2";
  // Styles: Rest
  export let restBase = "";
  export let restHeading = "";
  // Styles: Shared
  export let background = "bg-slate-800";
</script>

<a {href} class="{elemBase} {background} {restBase}">
  <h2 class="{elemHeading} {restHeading}">{@html title}</h2>
  <p>{@html body}</p>
</a>
