// src/components/Card.jsx
// import React, { useState } from 'react';

export default function Card({
  // Props (settings)
  href,
  title,
  body,
  // Props (styles)
  elemBase = "card",
  elemHeading = "h2",
  regionBase = "",
  regionHeading = "",
  background = "bg-slate-800",
}) {
  return (
      <>
        <a href={href} className={[`${elemBase} ${background} ${regionBase}`]}>
          <h2 className={[`${elemHeading} ${regionHeading}`]}>{title}</h2>
          <p>{body}</p>
        </a>
      </>
  )
};

// src/components/Card.svelte
<script lang="ts">
  // Props (settings)
  export let href: string;
  export let title: string;
  export let body: string;

  // Props (styles)
  export let elemBase = "card";
  export let elemHeading = "h2";
  // Styles: Regions
  export let regionBase = "";
  export let regionHeading = "";
  // Styles: Shared
  export let background = "bg-slate-800";
</script>

<a {href} class="{elemBase} {background} {regionBase}">
  <h2 class="{elemHeading} {regionHeading}">{@html title}</h2>
  <p>{@html body}</p>
</a>
